### ISSUE TITLE
Don't reboot in the middle of a dsc run

### ISSUE THREAD

**Issue by TraGicCode** [perktime/MoveAzureTempDrive#2]
I'm pretty sure you shouldn't be rebooting in the middle of a DSC run and should be informing the LCM that one is needed.

**Comment by carlosvsilva** [comment]
How would you do this then? Since removing the pagefile requires a reboot. 
Btw, how does one launch this script from the azure cli ? 
What values do I fill in --settings here? Thank you
az vm extension set \
   --name DSC \
   --publisher Microsoft.Powershell \
   --version 2.19 \
   --vm-name "$newMasterVMInstance" \
   --resource-group "$vmResourceGroup" \
   --settings '{"ModulesURL":"https://github.com/Azure/azure-quickstart-templates/raw/master/dsc-extension-iis-server-windows-vm/ContosoWebsite.ps1.zip", "configurationFunction": "ContosoWebsite.ps1\\ContosoWebsite", "Properties": {"MachineName": "myVM"} }'
